---
name: rcmpy
version: "{{major}}.{{minor}}.{{patch}}"
description: A configuration-file management system.
entry: {{entry}}
requirements: []
dev_requirements:
  - vcorelib
  - setuptools-wrapper
  - types-setuptools
