---
name: rcmpy
version: "{{major}}.{{minor}}.{{patch}}"
description: A configuration-file management system.
entry: {{entry}}
requirements:
  - datazen
  - vcorelib>=1.5.0
dev_requirements:
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: apply
    description: apply any pending changes from the active data repository
  - name: use
    description: set the directory to use as the rcmpy data repository
  - name: variant
    description: set the variant of configuration data to use
  - name: watch
    description: do a task whenever a file in a specified directory changes
